// 默认配置。单独成模块是为了让测试能直接断言默认值（比如新装默认节点是内置引擎），
// 而不用真的起一个服务 —— 起服务会顺带按 autoLaunchGale 把 Gale 拉起来，测试里不该有这种副作用。

export const DEFAULT_CONFIG = {
  provider: 'builtin',
  // 语言包没下好 / 浏览器不支持时，自动兜底到免费节点，保证新用户开箱就能看到中文
  fallback: ['tencent', 'youdao'],
  target: 'zh-CN',
  source: 'auto',
  proxy: '',
  // 翻译节点管理：disabledSources 停用内置源；customSources 为用户自建节点
  disabledSources: [],
  customSources: [],
  galePath: 'D:\\Gale\\gale.exe',
  autoLaunchGale: true,
  servicePort: 8799,
  cdpPort: 9223,
  translateNames: false,
  translateConfigPage: true,
  hoverOriginal: true,
  chineseSearch: true,
  // 模糊复用：只差版本号 / 标点 / 空白的句子直接用已有译文（零请求）
  fuzzyReuse: true,
  // 插件自身界面语言：'zh-CN' | 'en'
  uiLang: 'zh-CN',
  // 内置引擎在本环境用不了时，**要不要自动把 provider 换到在线节点**。
  //
  // 默认**关**（1.4 起）：这是个开源插件，新装就被悄悄切到第三方节点，
  // 等于在用户不知情的情况下把要翻译的文本发出去（各家条款与隐私政策都不一样）。
  // 现在内置引擎有两条后端（Gale 页面，或插件自己拉起的 Edge，见 edge-worker.mjs），
  // 实在都用不了时会在界面里说清楚原因、让用户自己挑一个节点，而不是替他决定。
  autoSwitchFromBuiltin: false,
  // 仅本地模式（禁用联网）：只允许"请求不出本机"的翻译节点（内置引擎、本地大模型、
  // 本机自建的 LibreTranslate、仅用缓存），并在 net.mjs 里把所有对外请求硬拦掉。
  //
  // 默认关：开了它就只能用「请求不出本机」的节点（内置引擎、本地大模型、本机 LibreTranslate、仅用缓存）。
  // 用途有两个：① 完全规避第三方条款与隐私风险（开源插件给不确定的用户用）；
  // ② 验证本地引擎/本地模型到底翻得怎么样 —— 开着它就不可能"偷偷"把文本发给在线节点。
  offlineOnly: false,
  forceTranslate: [],
  // 译文质量：fast = 单节点直出；best = 多节点并发 + 质量评分择优（列表/摘要等短文本才走）
  quality: { mode: 'fast', voters: [], consistency: true },
  // LLM 润色：机翻先上屏，再用大模型润色并回推替换
  polish: { enabled: false, minLen: 10, batchSize: 8 },
  // 公共译库：与翻译节点无关的共享译文层
  library: { autoCollect: true },
  minLen: 3,
  glossary: [
    'Valheim',
    'BepInEx',
    'Jotunn',
    'Harmony',
    'Thunderstore',
    'Hexium',
    'Gale',
    'Unity',
    'Steam',
    'mod',
  ],
  postReplace: [
    { from: '瓦尔海姆', to: '英灵神殿' },
    { from: '香草', to: '原版' },
    { from: '华为开源', to: '开源' },
  ],
  // 固定译法：整段文本完全匹配时直接使用，不走机翻（更准、零请求）
  phraseMap: {
    'quality of life': '生活质量',
    'client (& server)': '客户端与服务端',
    'client & server': '客户端与服务端',
    'client and server': '客户端与服务端',
    'client-side': '客户端',
    'client side': '客户端',
    'server-side': '服务端',
    'server side': '服务端',
    mechanics: '玩法机制',
    'open source': '开源',
    modpack: '整合包',
    modpacks: '整合包',
    mods: '模组',
    tools: '工具',
    library: '库',
    libraries: '库',
    items: '物品',
    balance: '平衡性',
    audio: '音频',
    graphics: '画面',
    models: '模型',
    textures: '材质',
    localization: '本地化',
    monsters: '怪物',
    enemies: '敌人',
    ui: '界面',
    'world generation': '世界生成',
    tweaks: '调整',
    utility: '实用工具',
    gear: '装备',
    misc: '杂项',
    client: '客户端',
    server: '服务端',
    cosmetics: '外观',
    map: '地图',
    quests: '任务',
    skills: '技能',
    crafting: '制作',
    building: '建筑',
    npcs: 'NPC',
    weather: '天气',
    performance: '性能',
    optimization: '优化',
    multiplayer: '多人',
    devtools: '开发工具',
    'hildir\'s request update': '希尔迪尔的请求更新',
    'bog witch update': '沼泽女巫更新',
    'ashlands update': '灰烬之地更新',
    'mistlands update': '迷雾之地更新',
    features: '功能特点',
    introduction: '简介',
    compatibility: '兼容性',
    'other info': '其他信息',
    contact: '联系作者',
    installation: '安装方法',
    installing: '安装',
    'manual installation': '手动安装',
    'installation instructions': '安装说明',
    'installation through r2modman or thunderstore mod manager': '通过 r2modman 或 Thunderstore Mod Manager 安装',
    changelog: '更新日志',
    config: '配置',
    credits: '鸣谢',
    configuration: '配置',
    requirements: '前置要求',
    dependencies: '依赖项',
    'known issues': '已知问题',
    usage: '使用方法',
    faq: '常见问题',
    overview: '概述',
    description: '简介',
    support: '支持',
    license: '许可协议',
    notes: '说明',
    contents: '内容',
    screenshots: '截图',
    translations: '翻译',
    source: '源码',
    links: '相关链接',
    wiki: '维基',
    menu: '菜单',
    install: '安装',
    'deep north update': '极北之境更新',
    'launch the game.': '启动游戏。',
  },
  deeplKey: '',
  openaiBaseUrl: 'https://api.deepseek.com/v1',
  openaiKey: '',
  openaiModel: 'deepseek-chat',
  localLlmBaseUrl: 'http://127.0.0.1:11434/v1',
  localLlmModel: 'qwen2.5:7b',
  localLlmKey: '',
  libreUrl: '',
  libreKey: '',
};
